[package]
name = "ulid"
version = "0.3.3"
authors = ["dylanhart <dylan96hart@gmail.com>"]
edition = "2018"

license = "MIT"
readme = "README.md"

description = "a Universally Unique Lexicographically Sortable Identifier implementation"
keywords = ["ulid", "uuid", "sortable", "identifier"]

repository = "https://github.com/dylanhart/ulid-rs"

[dependencies]
lazy_static = "1.2"
serde = { version = "1.0", features = ["derive"], optional = true }
# -- Sync versions with the WASM target below --
chrono = "0.4"
rand = "0.6"
uuid = { version = "0.8", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# -- Sync versions with non-WASM targets above --
chrono = { version = "0.4", features = ["wasmbind"] }
rand = { version = "0.6", features = ["wasm-bindgen"] }
uuid = { version = "0.8", features = ["wasm-bindgen"], optional = true }

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false

[workspace]
members = ["cli"]

[package.metadata.docs.rs]
all-features = true
